apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nats.service.name }}
  namespace: {{ include "easylab.namespace" . }}
  labels:
    {{- include "easylab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nats.service.type }}
  selector:
    app: {{ .Values.nats.service.name }}
  ports:
    - name: client
      port: 4222
      targetPort: 4222
      protocol: TCP
    - name: monitor
      port: 8222
      targetPort: 8222
      protocol: TCP
