apiVersion: v1
kind: Service
metadata:
  name: {{ include "easylab.name" . }}
  namespace: {{ include "easylab.namespace" . }}
  labels:
    {{- include "easylab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    app: {{ include "easylab.name" . }}
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: 8080
      protocol: TCP
