{{- if .Values.selenium.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.selenium.service.name }}
  namespace: {{ include "easylab.namespace" . }}
  labels:
    {{- include "easylab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.selenium.service.type }}
  selector:
    app: {{ .Values.selenium.service.name }}
  ports:
    - name: http
      port: {{ .Values.selenium.port }}
      targetPort: {{ .Values.selenium.port }}
      protocol: TCP
{{- end }}
